[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  query = {id = ":id"}
  status = 200

[[redirects]]
   from = "/*"
  to = "/index.html"
  query = {termino = ":termino"}
  status = 200